<?php
/*
 * Generated by CRUDigniter v2.3 Beta
 * www.crudigniter.com
 */

class Admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Admin_model');
    }

    /*
     * Listing of admin
     */
    function index()
    {
        $data['admin'] = $this->Admin_model->get_all_admin();

        $this->load->view('admin/index',$data);
    }

    /*
     * Adding a new admin
     */
    function add()
    {
        $this->load->library('form_validation');

		$this->form_validation->set_rules('nombre','Nombre','required|max_length[50]');
		$this->form_validation->set_rules('usurio','Usurio','required|max_length[30]');
		$this->form_validation->set_rules('clave','Clave','required|max_length[20]');

		if($this->form_validation->run())
        {
            $params = array(
				'nombre' => $this->input->post('nombre'),
				'usurio' => $this->input->post('usurio'),
				'clave' => $this->input->post('clave'),
            );

            $admin_id = $this->Admin_model->add_admin($params);
            redirect('admin/index');
        }
        else
        {
            $this->load->view('admin/add');
        }
    }

    /*
     * Editing a admin
     */
    function edit($id)
    {
        // check if the admin exists before trying to edit it
        $admin = $this->Admin_model->get_admin($id);

        if(isset($admin['id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('nombre','Nombre','required|max_length[50]');
			$this->form_validation->set_rules('usurio','Usurio','required|max_length[30]');
			$this->form_validation->set_rules('clave','Clave','required|max_length[20]');

			if($this->form_validation->run())
            {
                $params = array(
					'nombre' => $this->input->post('nombre'),
					'usurio' => $this->input->post('usurio'),
					'clave' => $this->input->post('clave'),
                );

                $this->Admin_model->update_admin($id,$params);
                redirect('admin/index');
            }
            else
            {
                $data['admin'] = $this->Admin_model->get_admin($id);

                $this->load->view('admin/edit',$data);
            }
        }
        else
            show_error('The admin you are trying to edit does not exist.');
    }

    /*
     * Deleting admin
     */
    function remove($id)
    {
        $admin = $this->Admin_model->get_admin($id);

        // check if the admin exists before trying to delete it
        if(isset($admin['id']))
        {
            $this->Admin_model->delete_admin($id);
            redirect('admin/index');
        }
        else
            show_error('The admin you are trying to delete does not exist.');
    }

}
